tasks:
- source: scripts/get.py
  product:
    nb: products/get.ipynb
    data: products/get.csv
  
- source: scripts/process.py
  product:
    nb: products/process.ipynb
    data: products/process.csv

- source: scripts/model.py
  product: products/model.ipynb
