tasks:
- source: scripts/get.py
  product:
    nb: products/get.ipynb
    train: products/train.csv
    test: products/test.csv
  
- source: scripts/process_model.py
  product: products/process_model.ipynb